### ISSUE TITLE
Add Mark Heath's video set on MoreLINQ

### ISSUE THREAD

**Issue by atifaziz** [morelinq/morelinq.github.io#3]
Add the following [introductory videos](https://www.youtube.com/watch?v=LmeTMUptJPo&list=PLzUdt2T2KyAdVmA681z98tpLQSagXBLdP) by @markheath for a bunch of MoreLINQ methods:

- [ ] [`EquiZip`, `ZipLongest`, `ZipShortest`](https://youtu.be/LmeTMUptJPo);
  see also [Exploring MoreLINQ Part 1 - Zipping](https://markheath.net/post/exploring-morelinq-1-zipping)
- [ ] [`AtLeast`, `AtMost`, `Exactly`, `CountBetween`, `AssertCount`](https://youtu.be/1dheBYmLdV8);
  see also [Exploring MoreLINQ Part 2 - Counting Elements](https://markheath.net/post/exploring-morelinq-2-counting)
- [ ] [`MinBy`, `MaxBy`](https://youtu.be/69vgji_r3iQ);
  see also [Exploring MoreLINQ Part 3 - MinBy and MaxBy](https://markheath.net/post/exploring-morelinq-3-maxby)
- [ ] [`Permutations`, `Subset`, `Cartesian`](https://youtu.be/1_-SLmSykig);
  see also [Exploring MoreLINQ Part 4 - Combinations](https://markheath.net/post/exploring-morelinq-4-combinations)
- [ ] [`Scan`, `ScanRight`, `PreScan`](https://youtu.be/KJUfv_AfFBE);
  see also [Exploring MoreLINQ Part 5 - Scan](https://markheath.net/post/exploring-morelinq-5-scan)
- [ ] [`TakeLast`, `TakeUntil` and `TakeEvery`](https://youtu.be/YwReGiQYBG8);
  see also [Exploring MoreLINQ Part 6 - Taking](https://markheath.net/post/exploring-morelinq-6-taking)
- [ ] [`Batch`](https://youtu.be/HPf5lk9BRy0);
  see also [Exploring MoreLINQ Part 7 - Batching](https://markheath.net/post/exploring-morelinq-7-batching)
- [ ] [`FallbackIfEmpty`](https://youtu.be/DfF6bjDOB-0);
  see also [Exploring MoreLINQ Part 8 - FallbackIfEmpty](https://markheath.net/post/exploring-morelinq-8-fallback-if-empty)
- [ ] [`FillForward`, `FillBackward`](https://youtu.be/RUWNkeSSc9A);
  see also [Exploring MoreLINQ Part 9 - FillForward](https://markheath.net/post/exploring-morelinq-9-fill-forward)
- [ ] [`Interleave`](https://youtu.be/kJbUW7Y_IEY);
  see also [Exploring MoreLINQ Part 10 - Interleave](https://markheath.net/post/exploring-morelinq-10-interleave)
- [ ] [`PadStart`, `Pad`](https://youtu.be/YQ9tucuYA8c);
  see also [Exploring MoreLINQ Part 11 - Padding](https://markheath.net/post/exploring-morelinq-11-padding)
- [ ] [`RunLengthEncode`](https://youtu.be/MT3ut1MfiwQ);
  see also [Exploring MoreLINQ Part 12 - Run Length Encoding](https://markheath.net/post/exploring-morelinq-12-run-length-encoding)
- [ ] [`Random`, `RandomDouble`, `RandomSubset`, `Shuffle`](https://youtu.be/tOn4X8CEBzs);
  see also [Exploring MoreLINQ Part 13 - Random Sequences](https://markheath.net/post/exploring-morelinq-13-random)
- [ ] [`SkipUntil`, `SkipLast`, `Slice`](https://youtu.be/RYDJefbHyqI);
  see also [Exploring MoreLINQ Part 14 - Skipping and Slicing](https://markheath.net/post/exploring-morelinq-14-skipping)
- [ ] [`Window`, `WindowLeft`, `WindowRight`](https://youtu.be/VMPKjsh3L-g);
  see also [Exploring MoreLINQ Part 15 - Windowing](https://markheath.net/post/exploring-morelinq-15-windowing)
- [ ] [`Pairwise` (and resolving ambiguities)](https://youtu.be/VqCa0wgdqTc);
  see also [Exploring MoreLINQ Part 16 - Pairwise and Resolving Ambiguities](https://markheath.net/post/exploring-morelinq-16-pairwise)
- [ ] [`CountBy`](https://youtu.be/vbijoQIWcA8);
  see also [Exploring MoreLINQ Part 17 - CountBy](https://markheath.net/post/exploring-morelinq-17-countby)
- [ ] [`GroupAdjacent`, `Segment`](https://youtu.be/M_MzMtiudQA);
  see also [Exploring MoreLINQ Part 18 - GroupAdjacent and Segment](https://markheath.net/post/exploring-morelinq-18-groupadjacent)
- [ ] [`Generate`, `GenerateByIndex`, `Repeat`, `Sequence`, `Unfold`](https://youtu.be/2c6GqXzlkE0);
  see also [Exploring MoreLINQ Part 19 - Generating sequences](https://markheath.net/post/exploring-morelinq-19-generate)
- [ ] [`ToDelimitedString`, `ToDictionary`, `ToHashSet`, `ToArrayByIndex`](https://youtu.be/rBIn2Z5v6Oc);
  see also [Exploring MoreLINQ Part 20 - ToDelimitedString (and friends)](https://markheath.net/post/exploring-morelinq-20-todelimitedstring)
- [ ] [`Trace`, `Pipe`, `ForEach`, `Consume`](https://youtu.be/SwCOGVl52R8);
  see also [Exploring MoreLINQ Part 21 - Side Effects](https://markheath.net/post/exploring-morelinq-21-sideeffects)
- [ ] [`Append`, `Prepend`, `Insert`, `Backsert`](https://youtu.be/ckni4GgO3ao);
  see also [Exploring MoreLINQ Part 22 - Append and Prepend](https://markheath.net/post/exploring-morelinq-22-append-prepend)
- [ ] [`RightJoin`, `LeftJoin`, `FullJoin`, `FullGroupJoin`](https://youtu.be/xszWqX3tcr8);
  see also [Exploring MoreLINQ Part 23 - Joining](https://markheath.net/post/exploring-morelinq-23-joining)
- [ ] [`Flatten`](https://youtu.be/5EukD_4Khw0);
  see also [Exploring MoreLINQ Part 24 - Flatten](https://markheath.net/post/exploring-morelinq-24-flatten)

This will go a long way to help with morelinq/MoreLINQ#189.

**Comment by ErPuneetGoel** [comment]
I need help to implement Lead/Lag function of MoreLinq in my project. Can you please suggest some example ?

**Comment by atifaziz** [comment]
@ErPuneetGoel This is not the right place to ask your question. This is the issue tracker for the project web site. Ask on [StackOverflow](https://stackoverflow.com/) instead.
